// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	docker "sps/internal/docker"

	io "io"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AttachExec provides a mock function with given fields: ctx, id, cmd, stdin, stdout, stderr, tty
func (_m *MockClient) AttachExec(ctx context.Context, id string, cmd []string, stdin io.Reader, stdout io.Writer, stderr io.Writer, tty bool) (string, int, error) {
	ret := _m.Called(ctx, id, cmd, stdin, stdout, stderr, tty)

	if len(ret) == 0 {
		panic("no return value specified for AttachExec")
	}

	var r0 string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, io.Reader, io.Writer, io.Writer, bool) (string, int, error)); ok {
		return rf(ctx, id, cmd, stdin, stdout, stderr, tty)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, io.Reader, io.Writer, io.Writer, bool) string); ok {
		r0 = rf(ctx, id, cmd, stdin, stdout, stderr, tty)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, io.Reader, io.Writer, io.Writer, bool) int); ok {
		r1 = rf(ctx, id, cmd, stdin, stdout, stderr, tty)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []string, io.Reader, io.Writer, io.Writer, bool) error); ok {
		r2 = rf(ctx, id, cmd, stdin, stdout, stderr, tty)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_AttachExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachExec'
type MockClient_AttachExec_Call struct {
	*mock.Call
}

// AttachExec is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - cmd []string
//   - stdin io.Reader
//   - stdout io.Writer
//   - stderr io.Writer
//   - tty bool
func (_e *MockClient_Expecter) AttachExec(ctx interface{}, id interface{}, cmd interface{}, stdin interface{}, stdout interface{}, stderr interface{}, tty interface{}) *MockClient_AttachExec_Call {
	return &MockClient_AttachExec_Call{Call: _e.mock.On("AttachExec", ctx, id, cmd, stdin, stdout, stderr, tty)}
}

func (_c *MockClient_AttachExec_Call) Run(run func(ctx context.Context, id string, cmd []string, stdin io.Reader, stdout io.Writer, stderr io.Writer, tty bool)) *MockClient_AttachExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(io.Reader), args[4].(io.Writer), args[5].(io.Writer), args[6].(bool))
	})
	return _c
}

func (_c *MockClient_AttachExec_Call) Return(_a0 string, _a1 int, _a2 error) *MockClient_AttachExec_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_AttachExec_Call) RunAndReturn(run func(context.Context, string, []string, io.Reader, io.Writer, io.Writer, bool) (string, int, error)) *MockClient_AttachExec_Call {
	_c.Call.Return(run)
	return _c
}

// Build provides a mock function with given fields: ctx, opts, log
func (_m *MockClient) Build(ctx context.Context, opts docker.BuildOptions, log io.Writer) error {
	ret := _m.Called(ctx, opts, log)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, docker.BuildOptions, io.Writer) error); ok {
		r0 = rf(ctx, opts, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockClient_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - opts docker.BuildOptions
//   - log io.Writer
func (_e *MockClient_Expecter) Build(ctx interface{}, opts interface{}, log interface{}) *MockClient_Build_Call {
	return &MockClient_Build_Call{Call: _e.mock.On("Build", ctx, opts, log)}
}

func (_c *MockClient_Build_Call) Run(run func(ctx context.Context, opts docker.BuildOptions, log io.Writer)) *MockClient_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(docker.BuildOptions), args[2].(io.Writer))
	})
	return _c
}

func (_c *MockClient_Build_Call) Return(_a0 error) *MockClient_Build_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Build_Call) RunAndReturn(run func(context.Context, docker.BuildOptions, io.Writer) error) *MockClient_Build_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, spec
func (_m *MockClient) Create(ctx context.Context, spec docker.Spec) (string, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, docker.Spec) (string, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, docker.Spec) string); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, docker.Spec) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spec docker.Spec
func (_e *MockClient_Expecter) Create(ctx interface{}, spec interface{}) *MockClient_Create_Call {
	return &MockClient_Create_Call{Call: _e.mock.On("Create", ctx, spec)}
}

func (_c *MockClient_Create_Call) Run(run func(ctx context.Context, spec docker.Spec)) *MockClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(docker.Spec))
	})
	return _c
}

func (_c *MockClient_Create_Call) Return(_a0 string, _a1 error) *MockClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Create_Call) RunAndReturn(run func(context.Context, docker.Spec) (string, error)) *MockClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureNetwork provides a mock function with given fields: ctx, name
func (_m *MockClient) EnsureNetwork(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for EnsureNetwork")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_EnsureNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureNetwork'
type MockClient_EnsureNetwork_Call struct {
	*mock.Call
}

// EnsureNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockClient_Expecter) EnsureNetwork(ctx interface{}, name interface{}) *MockClient_EnsureNetwork_Call {
	return &MockClient_EnsureNetwork_Call{Call: _e.mock.On("EnsureNetwork", ctx, name)}
}

func (_c *MockClient_EnsureNetwork_Call) Run(run func(ctx context.Context, name string)) *MockClient_EnsureNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_EnsureNetwork_Call) Return(_a0 error) *MockClient_EnsureNetwork_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_EnsureNetwork_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_EnsureNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: ctx, id, cmd, tty
func (_m *MockClient) Exec(ctx context.Context, id string, cmd []string, tty bool) (docker.ExecResult, error) {
	ret := _m.Called(ctx, id, cmd, tty)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 docker.ExecResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, bool) (docker.ExecResult, error)); ok {
		return rf(ctx, id, cmd, tty)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, bool) docker.ExecResult); ok {
		r0 = rf(ctx, id, cmd, tty)
	} else {
		r0 = ret.Get(0).(docker.ExecResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, bool) error); ok {
		r1 = rf(ctx, id, cmd, tty)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockClient_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - cmd []string
//   - tty bool
func (_e *MockClient_Expecter) Exec(ctx interface{}, id interface{}, cmd interface{}, tty interface{}) *MockClient_Exec_Call {
	return &MockClient_Exec_Call{Call: _e.mock.On("Exec", ctx, id, cmd, tty)}
}

func (_c *MockClient_Exec_Call) Run(run func(ctx context.Context, id string, cmd []string, tty bool)) *MockClient_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(bool))
	})
	return _c
}

func (_c *MockClient_Exec_Call) Return(_a0 docker.ExecResult, _a1 error) *MockClient_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Exec_Call) RunAndReturn(run func(context.Context, string, []string, bool) (docker.ExecResult, error)) *MockClient_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Inspect provides a mock function with given fields: ctx, id
func (_m *MockClient) Inspect(ctx context.Context, id string) (docker.Container, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 docker.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (docker.Container, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) docker.Container); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(docker.Container)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockClient_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClient_Expecter) Inspect(ctx interface{}, id interface{}) *MockClient_Inspect_Call {
	return &MockClient_Inspect_Call{Call: _e.mock.On("Inspect", ctx, id)}
}

func (_c *MockClient_Inspect_Call) Run(run func(ctx context.Context, id string)) *MockClient_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Inspect_Call) Return(_a0 docker.Container, _a1 error) *MockClient_Inspect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Inspect_Call) RunAndReturn(run func(context.Context, string) (docker.Container, error)) *MockClient_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function with given fields: ctx, id, tail, out
func (_m *MockClient) Logs(ctx context.Context, id string, tail string, out io.Writer) error {
	ret := _m.Called(ctx, id, tail, out)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Writer) error); ok {
		r0 = rf(ctx, id, tail, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type MockClient_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tail string
//   - out io.Writer
func (_e *MockClient_Expecter) Logs(ctx interface{}, id interface{}, tail interface{}, out interface{}) *MockClient_Logs_Call {
	return &MockClient_Logs_Call{Call: _e.mock.On("Logs", ctx, id, tail, out)}
}

func (_c *MockClient_Logs_Call) Run(run func(ctx context.Context, id string, tail string, out io.Writer)) *MockClient_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(io.Writer))
	})
	return _c
}

func (_c *MockClient_Logs_Call) Return(_a0 error) *MockClient_Logs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Logs_Call) RunAndReturn(run func(context.Context, string, string, io.Writer) error) *MockClient_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockClient) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Ping(ctx interface{}) *MockClient_Ping_Call {
	return &MockClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockClient_Ping_Call) Run(run func(ctx context.Context)) *MockClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_Ping_Call) Return(_a0 error) *MockClient_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Ping_Call) RunAndReturn(run func(context.Context) error) *MockClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Ports provides a mock function with given fields: ctx, id
func (_m *MockClient) Ports(ctx context.Context, id string) ([]docker.Port, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Ports")
	}

	var r0 []docker.Port
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]docker.Port, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []docker.Port); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]docker.Port)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Ports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ports'
type MockClient_Ports_Call struct {
	*mock.Call
}

// Ports is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClient_Expecter) Ports(ctx interface{}, id interface{}) *MockClient_Ports_Call {
	return &MockClient_Ports_Call{Call: _e.mock.On("Ports", ctx, id)}
}

func (_c *MockClient_Ports_Call) Run(run func(ctx context.Context, id string)) *MockClient_Ports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Ports_Call) Return(_a0 []docker.Port, _a1 error) *MockClient_Ports_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Ports_Call) RunAndReturn(run func(context.Context, string) ([]docker.Port, error)) *MockClient_Ports_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: ctx, id, path
func (_m *MockClient) ReadFile(ctx context.Context, id string, path string) ([]byte, error) {
	ret := _m.Called(ctx, id, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return rf(ctx, id, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, id, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockClient_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - path string
func (_e *MockClient_Expecter) ReadFile(ctx interface{}, id interface{}, path interface{}) *MockClient_ReadFile_Call {
	return &MockClient_ReadFile_Call{Call: _e.mock.On("ReadFile", ctx, id, path)}
}

func (_c *MockClient_ReadFile_Call) Run(run func(ctx context.Context, id string, path string)) *MockClient_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_ReadFile_Call) Return(_a0 []byte, _a1 error) *MockClient_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ReadFile_Call) RunAndReturn(run func(context.Context, string, string) ([]byte, error)) *MockClient_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, id, force
func (_m *MockClient) Remove(ctx context.Context, id string, force bool) error {
	ret := _m.Called(ctx, id, force)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockClient_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - force bool
func (_e *MockClient_Expecter) Remove(ctx interface{}, id interface{}, force interface{}) *MockClient_Remove_Call {
	return &MockClient_Remove_Call{Call: _e.mock.On("Remove", ctx, id, force)}
}

func (_c *MockClient_Remove_Call) Run(run func(ctx context.Context, id string, force bool)) *MockClient_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockClient_Remove_Call) Return(_a0 error) *MockClient_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Remove_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockClient_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// ResizeTTY provides a mock function with given fields: ctx, execID, height, width
func (_m *MockClient) ResizeTTY(ctx context.Context, execID string, height int, width int) error {
	ret := _m.Called(ctx, execID, height, width)

	if len(ret) == 0 {
		panic("no return value specified for ResizeTTY")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) error); ok {
		r0 = rf(ctx, execID, height, width)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_ResizeTTY_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeTTY'
type MockClient_ResizeTTY_Call struct {
	*mock.Call
}

// ResizeTTY is a helper method to define mock.On call
//   - ctx context.Context
//   - execID string
//   - height int
//   - width int
func (_e *MockClient_Expecter) ResizeTTY(ctx interface{}, execID interface{}, height interface{}, width interface{}) *MockClient_ResizeTTY_Call {
	return &MockClient_ResizeTTY_Call{Call: _e.mock.On("ResizeTTY", ctx, execID, height, width)}
}

func (_c *MockClient_ResizeTTY_Call) Run(run func(ctx context.Context, execID string, height int, width int)) *MockClient_ResizeTTY_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockClient_ResizeTTY_Call) Return(_a0 error) *MockClient_ResizeTTY_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_ResizeTTY_Call) RunAndReturn(run func(context.Context, string, int, int) error) *MockClient_ResizeTTY_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, spec
func (_m *MockClient) Run(ctx context.Context, spec docker.Spec) (string, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, docker.Spec) (string, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, docker.Spec) string); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, docker.Spec) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockClient_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - spec docker.Spec
func (_e *MockClient_Expecter) Run(ctx interface{}, spec interface{}) *MockClient_Run_Call {
	return &MockClient_Run_Call{Call: _e.mock.On("Run", ctx, spec)}
}

func (_c *MockClient_Run_Call) Run(run func(ctx context.Context, spec docker.Spec)) *MockClient_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(docker.Spec))
	})
	return _c
}

func (_c *MockClient_Run_Call) Return(_a0 string, _a1 error) *MockClient_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Run_Call) RunAndReturn(run func(context.Context, docker.Spec) (string, error)) *MockClient_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, id
func (_m *MockClient) Start(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClient_Expecter) Start(ctx interface{}, id interface{}) *MockClient_Start_Call {
	return &MockClient_Start_Call{Call: _e.mock.On("Start", ctx, id)}
}

func (_c *MockClient_Start_Call) Run(run func(ctx context.Context, id string)) *MockClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Start_Call) Return(_a0 error) *MockClient_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Start_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx, id, timeout
func (_m *MockClient) Stop(ctx context.Context, id string, timeout time.Duration) error {
	ret := _m.Called(ctx, id, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, id, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockClient_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - timeout time.Duration
func (_e *MockClient_Expecter) Stop(ctx interface{}, id interface{}, timeout interface{}) *MockClient_Stop_Call {
	return &MockClient_Stop_Call{Call: _e.mock.On("Stop", ctx, id, timeout)}
}

func (_c *MockClient_Stop_Call) Run(run func(ctx context.Context, id string, timeout time.Duration)) *MockClient_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockClient_Stop_Call) Return(_a0 error) *MockClient_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Stop_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockClient_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: ctx, id, path, content
func (_m *MockClient) WriteFile(ctx context.Context, id string, path string, content []byte) error {
	ret := _m.Called(ctx, id, path, content)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, id, path, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockClient_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - path string
//   - content []byte
func (_e *MockClient_Expecter) WriteFile(ctx interface{}, id interface{}, path interface{}, content interface{}) *MockClient_WriteFile_Call {
	return &MockClient_WriteFile_Call{Call: _e.mock.On("WriteFile", ctx, id, path, content)}
}

func (_c *MockClient_WriteFile_Call) Run(run func(ctx context.Context, id string, path string, content []byte)) *MockClient_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockClient_WriteFile_Call) Return(_a0 error) *MockClient_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WriteFile_Call) RunAndReturn(run func(context.Context, string, string, []byte) error) *MockClient_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
