// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	events "sps/internal/events"

	mock "github.com/stretchr/testify/mock"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: after, limit
func (_m *MockReader) Read(after int64, limit int) ([]events.Event, error) {
	ret := _m.Called(after, limit)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []events.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) ([]events.Event, error)); ok {
		return rf(after, limit)
	}
	if rf, ok := ret.Get(0).(func(int64, int) []events.Event); ok {
		r0 = rf(after, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]events.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(after, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - after int64
//   - limit int
func (_e *MockReader_Expecter) Read(after interface{}, limit interface{}) *MockReader_Read_Call {
	return &MockReader_Read_Call{Call: _e.mock.On("Read", after, limit)}
}

func (_c *MockReader_Read_Call) Run(run func(after int64, limit int)) *MockReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *MockReader_Read_Call) Return(_a0 []events.Event, _a1 error) *MockReader_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_Read_Call) RunAndReturn(run func(int64, int) ([]events.Event, error)) *MockReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
