// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// SendPIN provides a mock function with given fields: ctx, email, pin
func (_m *MockMailer) SendPIN(ctx context.Context, email string, pin string) error {
	ret := _m.Called(ctx, email, pin)

	if len(ret) == 0 {
		panic("no return value specified for SendPIN")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailer_SendPIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPIN'
type MockMailer_SendPIN_Call struct {
	*mock.Call
}

// SendPIN is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - pin string
func (_e *MockMailer_Expecter) SendPIN(ctx interface{}, email interface{}, pin interface{}) *MockMailer_SendPIN_Call {
	return &MockMailer_SendPIN_Call{Call: _e.mock.On("SendPIN", ctx, email, pin)}
}

func (_c *MockMailer_SendPIN_Call) Run(run func(ctx context.Context, email string, pin string)) *MockMailer_SendPIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMailer_SendPIN_Call) Return(_a0 error) *MockMailer_SendPIN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailer_SendPIN_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMailer_SendPIN_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
