// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	events "sps/internal/events"

	mock "github.com/stretchr/testify/mock"
)

// MockEventLog is an autogenerated mock type for the EventLog type
type MockEventLog struct {
	mock.Mock
}

type MockEventLog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventLog) EXPECT() *MockEventLog_Expecter {
	return &MockEventLog_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: typ, data
func (_m *MockEventLog) Append(typ string, data map[string]any) (events.Event, error) {
	ret := _m.Called(typ, data)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 events.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]any) (events.Event, error)); ok {
		return rf(typ, data)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]any) events.Event); ok {
		r0 = rf(typ, data)
	} else {
		r0 = ret.Get(0).(events.Event)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]any) error); ok {
		r1 = rf(typ, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventLog_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockEventLog_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - typ string
//   - data map[string]any
func (_e *MockEventLog_Expecter) Append(typ interface{}, data interface{}) *MockEventLog_Append_Call {
	return &MockEventLog_Append_Call{Call: _e.mock.On("Append", typ, data)}
}

func (_c *MockEventLog_Append_Call) Run(run func(typ string, data map[string]any)) *MockEventLog_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]any))
	})
	return _c
}

func (_c *MockEventLog_Append_Call) Return(_a0 events.Event, _a1 error) *MockEventLog_Append_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventLog_Append_Call) RunAndReturn(run func(string, map[string]any) (events.Event, error)) *MockEventLog_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: after, limit
func (_m *MockEventLog) Read(after int64, limit int) ([]events.Event, error) {
	ret := _m.Called(after, limit)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []events.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) ([]events.Event, error)); ok {
		return rf(after, limit)
	}
	if rf, ok := ret.Get(0).(func(int64, int) []events.Event); ok {
		r0 = rf(after, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]events.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(after, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventLog_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockEventLog_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - after int64
//   - limit int
func (_e *MockEventLog_Expecter) Read(after interface{}, limit interface{}) *MockEventLog_Read_Call {
	return &MockEventLog_Read_Call{Call: _e.mock.On("Read", after, limit)}
}

func (_c *MockEventLog_Read_Call) Run(run func(after int64, limit int)) *MockEventLog_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *MockEventLog_Read_Call) Return(_a0 []events.Event, _a1 error) *MockEventLog_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventLog_Read_Call) RunAndReturn(run func(int64, int) ([]events.Event, error)) *MockEventLog_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventLog creates a new instance of MockEventLog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventLog {
	mock := &MockEventLog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
