// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	project "sps/internal/project"

	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: id, p
func (_m *MockStore) Create(id string, p project.Project) error {
	ret := _m.Called(id, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, project.Project) error); ok {
		r0 = rf(id, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - id string
//   - p project.Project
func (_e *MockStore_Expecter) Create(id interface{}, p interface{}) *MockStore_Create_Call {
	return &MockStore_Create_Call{Call: _e.mock.On("Create", id, p)}
}

func (_c *MockStore_Create_Call) Run(run func(id string, p project.Project)) *MockStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(project.Project))
	})
	return _c
}

func (_c *MockStore_Create_Call) Return(_a0 error) *MockStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Create_Call) RunAndReturn(run func(string, project.Project) error) *MockStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockStore_Expecter) Delete(id interface{}) *MockStore_Delete_Call {
	return &MockStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockStore_Delete_Call) Run(run func(id string)) *MockStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStore_Delete_Call) Return(_a0 error) *MockStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Delete_Call) RunAndReturn(run func(string) error) *MockStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockStore) Get(id string) (project.Project, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 project.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (project.Project, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) project.Project); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(project.Project)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockStore_Expecter) Get(id interface{}) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockStore_Get_Call) Run(run func(id string)) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(_a0 project.Project, _a1 error) *MockStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(string) (project.Project, error)) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockStore) List() ([]project.Entry, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []project.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]project.Entry, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []project.Entry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]project.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockStore_Expecter) List() *MockStore_List_Call {
	return &MockStore_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockStore_List_Call) Run(run func()) *MockStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_List_Call) Return(_a0 []project.Entry, _a1 error) *MockStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_List_Call) RunAndReturn(run func() ([]project.Entry, error)) *MockStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, p
func (_m *MockStore) Update(id string, p project.Project) error {
	ret := _m.Called(id, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, project.Project) error); ok {
		r0 = rf(id, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id string
//   - p project.Project
func (_e *MockStore_Expecter) Update(id interface{}, p interface{}) *MockStore_Update_Call {
	return &MockStore_Update_Call{Call: _e.mock.On("Update", id, p)}
}

func (_c *MockStore_Update_Call) Run(run func(id string, p project.Project)) *MockStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(project.Project))
	})
	return _c
}

func (_c *MockStore_Update_Call) Return(_a0 error) *MockStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Update_Call) RunAndReturn(run func(string, project.Project) error) *MockStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
